// SPDX-FileCopyrightText: 2026 VISUEL CONCEPT
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * PackML (OMAC / ISA-TR88.00.02) — STANDARD OPC UA interface catalog.
 *
 * The archetype of a mutualised book: PackML defines standard tag names and
 * values for packaging machines, so ONE catalog describes the interface of every
 * PackML-compliant machine of a line. The book therefore carries **no
 * `interface`** — it is the standard itself, bound to each machine's own OPC UA
 * server at check-in (many-to-many book relation).
 *
 * PackTags are grouped in three sets (ISA-TR88.00.02):
 *   - **Command** — drive the state machine and the machine's general behaviour
 *     (in OPC UA these are often exposed as Methods as well as variables);
 *   - **Status**  — current state/mode/speed and interlocks;
 *   - **Admin**   — counters, times, alarms and stop reasons.
 *
 * SOURCES: OPC Foundation "OPC UA for PackML — Common Object Model" (OPC 30050,
 * PackMLStatusObjectType / PackMLAdminObjectType / Command tags) and the OMAC
 * PackML Unit/Machine Implementation Guide; tag names cross-checked against a
 * vendor implementation (Schneider EIO0000002202) — `StateCurrent` DINT,
 * `UnitModeCurrent` DINT, `CurMachSpeed` REAL.
 *
 * ⚠️ PARTIAL/UNVERIFIED: the OPC Foundation reference pages could not be opened
 * directly (HTTP 403), so this catalog is a faithful but NON-EXHAUSTIVE subset
 * of PackTags, and the OPC UA NodeIds below are illustrative (`ns=4;s=…`) — a
 * real book is generated by browsing the machine's server or by ingesting the
 * companion-spec NodeSet2. Re-calibrate against the machine before check-in.
 *
 * PackML state model values (ISA-TR88.00.02), for reference:
 *   1 CLEARING · 2 STOPPED · 3 STARTING · 4 IDLE · 5 SUSPENDED · 6 EXECUTE ·
 *   7 STOPPING · 8 ABORTING · 9 ABORTED · 10 HOLDING · 11 HELD · 12 UNHOLDING ·
 *   13 SUSPENDING · 14 UNSUSPENDING · 15 RESETTING · 16 COMPLETING · 17 COMPLETE
 * UnitMode: 1 PRODUCTION · 2 MAINTENANCE · 3 MANUAL.
 * CntrlCmd: 1 RESET · 2 START · 3 STOP · 4 HOLD · 5 UNHOLD · 6 SUSPEND ·
 *   7 UNSUSPEND · 8 ABORT · 9 CLEAR.
 */

import {
  warn,
  buildOpcUaReference,
  opcUaLeafType,
  type AddressBook,
  type BookEntry,
  type TagAccess
} from '@visuelconcept/wui-eng-core';

/** One PackTag of the standard interface. */
interface PackTag {
  /** Dot path inside the PackML object (`Status.StateCurrent`, …). */
  path: string;
  /** OPC UA built-in datatype name. */
  dataType: string;
  access: TagAccess;
  comment: string;
  unit?: string;
}

const PACKML_TAGS: PackTag[] = [
  // --- Status ---------------------------------------------------------------
  { path: 'Status.StateCurrent', dataType: 'Int32', access: 'r', comment: 'État courant PackML (1..17)' },
  { path: 'Status.StateRequested', dataType: 'Int32', access: 'r', comment: 'État demandé' },
  { path: 'Status.StateChangeInProgress', dataType: 'Boolean', access: 'r', comment: 'Transition d’état en cours' },
  { path: 'Status.UnitModeCurrent', dataType: 'Int32', access: 'r', comment: 'Mode courant (1 Production, 2 Maintenance, 3 Manuel)' },
  { path: 'Status.UnitModeRequested', dataType: 'Int32', access: 'r', comment: 'Mode demandé' },
  { path: 'Status.UnitModeChangeInProgress', dataType: 'Boolean', access: 'r', comment: 'Changement de mode en cours' },
  { path: 'Status.MachSpeed', dataType: 'Double', access: 'r', comment: 'Vitesse consigne machine', unit: 'pcs/min' },
  { path: 'Status.CurMachSpeed', dataType: 'Double', access: 'r', comment: 'Vitesse courante machine', unit: 'pcs/min' },
  { path: 'Status.EquipmentInterlock.Blocked', dataType: 'Boolean', access: 'r', comment: 'Bloqué en aval (blocked)' },
  { path: 'Status.EquipmentInterlock.Starved', dataType: 'Boolean', access: 'r', comment: 'Manque en amont (starved)' },
  { path: 'Status.MaterialInterlock', dataType: 'Int32', access: 'r', comment: 'Verrouillage matière' },
  // --- Command --------------------------------------------------------------
  { path: 'Command.CntrlCmd', dataType: 'Int32', access: 'rw', comment: 'Commande d’état (2 Start, 3 Stop, 4 Hold, 8 Abort…)' },
  { path: 'Command.CmdChangeRequest', dataType: 'Boolean', access: 'rw', comment: 'Front de prise en compte de CntrlCmd' },
  { path: 'Command.UnitMode', dataType: 'Int32', access: 'rw', comment: 'Mode demandé' },
  { path: 'Command.UnitModeChangeRequest', dataType: 'Boolean', access: 'rw', comment: 'Front de changement de mode' },
  { path: 'Command.MachSpeed', dataType: 'Double', access: 'rw', comment: 'Consigne de vitesse', unit: 'pcs/min' },
  { path: 'Command.RemoteInterface[0].Ready', dataType: 'Boolean', access: 'rw', comment: 'Interface distante — prêt' },
  // --- Admin ----------------------------------------------------------------
  { path: 'Admin.ProdProcessedCount[0].Count', dataType: 'UInt32', access: 'r', comment: 'Produits traités (bons + défectueux)', unit: 'pcs' },
  { path: 'Admin.ProdDefectiveCount[0].Count', dataType: 'UInt32', access: 'r', comment: 'Produits défectueux', unit: 'pcs' },
  { path: 'Admin.ProdConsumedCount[0].Count', dataType: 'UInt32', access: 'r', comment: 'Matière consommée', unit: 'pcs' },
  { path: 'Admin.AccTimeSinceReset', dataType: 'UInt32', access: 'r', comment: 'Temps cumulé depuis reset', unit: 's' },
  { path: 'Admin.MachDesignSpeed', dataType: 'Double', access: 'r', comment: 'Vitesse nominale machine', unit: 'pcs/min' },
  { path: 'Admin.StopReason.ID', dataType: 'Int32', access: 'r', comment: 'Code du motif d’arrêt' },
  { path: 'Admin.Alarm[0].ID', dataType: 'Int32', access: 'r', comment: 'Identifiant d’alarme' },
  { path: 'Admin.Alarm[0].Value', dataType: 'Int32', access: 'r', comment: 'Valeur associée à l’alarme' }
];

/**
 * The PackML standard-interface catalog. `interface` is intentionally absent:
 * the standard describes the interface, each machine supplies its own server.
 * The illustrative NodeIds use the conventional `ns=4;s=<path>` form.
 */
export function packMlBook(): AddressBook {
  const entries: BookEntry[] = PACKML_TAGS.map((tag) => ({
    path: tag.path,
    sourceType: tag.dataType,
    leafType: opcUaLeafType(tag.dataType),
    access: tag.access,
    // Reference shown with a neutral connection placeholder; the real one is the
    // machine's OPC UA connection, injected at check-in.
    addresses: { opcua: buildOpcUaReference('<Machine>', `ns=4;s=${tag.path}`) },
    comment: tag.comment,
    unit: tag.unit
  }));
  return {
    id: 'book-packml-v101',
    name: 'PackML v1.01 (interface OPC UA standard)',
    provenance: {
      kind: 'nodeset',
      file: 'Opc.Ua.PackML.NodeSet2.xml',
      generatedAt: '2026-07-10T11:30:00.000Z',
      detail: 'OPC 30050 « OPC UA for PackML » / OMAC ISA-TR88.00.02 — PackTags Command · Status · Admin'
    },
    // interface intentionally absent → standard interface, bound per machine.
    entries,
    types: [
      {
        id: 'PackMLStatusObjectType',
        name: 'PackMLStatusObjectType',
        members: PACKML_TAGS.filter((t) => t.path.startsWith('Status.')).map((t) => ({
          path: t.path.slice('Status.'.length),
          sourceType: t.dataType,
          leafType: opcUaLeafType(t.dataType),
          comment: t.comment
        }))
      },
      {
        id: 'PackMLAdminObjectType',
        name: 'PackMLAdminObjectType',
        members: PACKML_TAGS.filter((t) => t.path.startsWith('Admin.')).map((t) => ({
          path: t.path.slice('Admin.'.length),
          sourceType: t.dataType,
          leafType: opcUaLeafType(t.dataType),
          comment: t.comment
        }))
      }
    ],
    warnings: [
      warn(
        'demo.packml-subset',
        'A representative SUBSET of PackTags (the OPC 30050 spec could not be opened directly) — recalibrate it with a browse of the machine, or by ingesting the spec NodeSet2.'
      ),
      warn('demo.packml-illustrative-nodeids', 'The NodeIds are illustrative (ns=4;s=…): the real namespace depends on the machine OPC UA server.')
    ]
  };
}
