/**
 * Builds dashboard widgets from a machine's configured datapoint bindings, so a
 * machine's State + parameters can be pushed to a custom dashboard via the
 * dashboard API ({@link DashboardService}).
 *
 * Layout produced (grid render type):
 *  - "État machine" KPI-list  (top-left)   — the state datapoint, live value
 *  - "Historique d'état" Gantt (top-right)  — the state datapoint, historic
 *  - "Paramètres" KPI-list    (full width)  — every configured KPI parameter
 *
 * Widget ids are deterministic (`mf-<machineId>-<kind>`) so re-exporting to the
 * same dashboard replaces the machine's widgets instead of duplicating them.
 *
 * The serialised settings shape mirrors the real WinCC OA StandardLibrary widget
 * files (data/WebUI/widgets-v2/StandardLibrary/Charts/{kpi-list,gantt}.widget.json):
 * each series item is a group whose `datapoint` data-point context spreads the
 * value/name/unit attributes; custom labels/units use the `custom<Field>` flags.
 * `settings.jsonFileName` points at the widget definition so the settings editor
 * can load its UI schema.
 */
import type { WuiWidgetDatapointSettings } from '@wincc-oa/wui-models/interfaces/wui-widget.js';
import type { MachineDef } from '../types.js';

interface Ctx {
  context: string;
  config: unknown;
}

const KPI_JSON_FILE = 'StandardLibrary/Charts/kpi-list.widget';
const GANTT_JSON_FILE = 'StandardLibrary/Charts/gantt.widget';
const ANCHOR_JSON_FILE = 'StandardLibrary/Media/anchor.widget';
/** Base path of the dashboard SPA (anchor hrefs must start with `/` or http). */
const ATELIER_BASE_URL = '/data/dashboard-wc/index.html#/fleet-3d/';
const GANTT_RANGE = 'now/d';
const KPI_MIN_COLS = 6;
const KPI_MIN_ROWS = 3;
const GANTT_MIN = 8;
const KPI_DEFINED = ['value', 'name', 'unit', 'format', 'alertColor'];
const GANTT_DEFINED = ['value', 'name'];

/** Prefix marking a widget as machine-generated (used to replace on re-export). */
export function machineWidgetPrefix(machineId: string): string {
  return `mf-${machineId}-`;
}

/** True when `widget` was generated by this module for the given machine. */
export function isMachineWidget(widget: { id: string }, machineId: string): boolean {
  return widget.id.startsWith(machineWidgetPrefix(machineId));
}

/**
 * Build the widget set representing a machine's State + parameters, always led
 * by a hyperlink back to the machine's atelier 3D page.
 */
export function buildMachineWidgets(
  machine: MachineDef,
  atelierId: string,
  atelierName?: string
): WuiWidgetDatapointSettings[] {
  const prefix = machineWidgetPrefix(machine.id);
  const widgets: WuiWidgetDatapointSettings[] = [
    anchorWidget(`${prefix}link`, atelierId, atelierName, 0, 0, 12, 4)
  ];
  if (machine.stateDp) {
    widgets.push(
      kpiWidget(`${prefix}kpistate`, 'État machine', [kpiSeriesItem('État', machine.stateDp)], 0, 4, 6, 4),
      ganttWidget(`${prefix}ganttstate`, "Historique d'état", machine.stateDp, 6, 4, 12, 8)
    );
  }
  const params = (machine.kpis ?? []).filter((k) => k.dp);
  if (params.length > 0) {
    const items = params.map((k) => kpiSeriesItem(k.label || k.key, k.dp ?? '', k.unit));
    widgets.push(kpiWidget(`${prefix}kpiparams`, 'Paramètres', items, 0, 12, 12, 4));
  }
  return widgets;
}

/** Dashboard settings for a freshly created machine dashboard. */
export function buildDashboardSettings(machine: MachineDef): Record<string, unknown> {
  return {
    icon: 'ontology',
    name: { 'en_US.utf8': `Machine — ${machine.name}` },
    renderType: 'grid',
    version: 2
  };
}

function groupCtx(config: Record<string, unknown>): Ctx {
  return { context: 'group', config };
}

function arrayCtx(items: Ctx[]): Ctx {
  return { context: 'array', config: items };
}

/** Title/subtitle block expected by the widget chrome (matches stored widgets). */
function generalBlock(title: string): Ctx {
  return groupCtx({
    title: groupCtx({ 'en_US.utf8': title }),
    titleAlignment: 'left',
    subtitle: groupCtx({ 'en_US.utf8': '' }),
    subtitleAlignment: 'center',
    linkTitle: groupCtx({ 'en_US.utf8': '' }),
    borderColor: '',
    backgroundColor: 'var(--theme-color-2)'
  });
}

/** One KPI-list series item: a data-point spreading value (+ custom label/unit). */
function kpiSeriesItem(label: string, dpName: string, unit?: string): Ctx {
  const config: Record<string, unknown> = {
    dpName,
    definedConfigs: KPI_DEFINED,
    name: label,
    customName: true,
    customAlertColor: true
  };
  if (unit) {
    config.unit = unit;
    config.customUnit = true;
  }
  return groupCtx({ datapoint: { context: 'data-point', config } });
}

/** One Gantt series item: a historic data-point + default value mapping. */
function ganttSeriesItem(title: string, dpName: string): Ctx {
  return groupCtx({
    datapoint: {
      context: 'data-point',
      config: {
        dpName,
        definedConfigs: GANTT_DEFINED,
        fetchMethod: 'historic',
        name: title,
        customName: true
      }
    },
    mapping: '0'
  });
}

// eslint-disable-next-line max-params -- positional grid placement reads clearly here
function anchorWidget(
  id: string,
  atelierId: string,
  atelierName: string | undefined,
  x: number,
  y: number,
  cols: number,
  rows: number
): WuiWidgetDatapointSettings {
  const label = atelierName ? `← Retour à l'atelier « ${atelierName} »` : "← Retour à l'atelier";
  return {
    id,
    version: 2,
    x,
    y,
    cols,
    rows,
    minCols: 4,
    minRows: 4,
    name: 'Atelier',
    settings: {
      jsonFileName: ANCHOR_JSON_FILE,
      general: generalBlock('Navigation'),
      config: groupCtx({
        href: `${ATELIER_BASE_URL}${atelierId}`,
        innerText: { context: 'translate', config: { 'en_US.utf8': label, 'fr_FR.utf8': label } },
        target: '_self',
        style: 'color: var(--theme-color-primary); font-weight: 600;'
      })
    },
    component: { styles: [], scripts: [], tagname: 'a' }
  } as WuiWidgetDatapointSettings;
}

// eslint-disable-next-line max-params -- positional grid placement reads clearly here
function kpiWidget(
  id: string,
  title: string,
  items: Ctx[],
  x: number,
  y: number,
  cols: number,
  rows: number
): WuiWidgetDatapointSettings {
  return {
    id,
    version: 2,
    x,
    y,
    cols,
    rows,
    minCols: KPI_MIN_COLS,
    minRows: KPI_MIN_ROWS,
    name: title,
    settings: {
      jsonFileName: KPI_JSON_FILE,
      general: generalBlock(title),
      config: groupCtx({ series: arrayCtx(items) })
    },
    component: { styles: [], scripts: ['kpi-list'], tagname: 'wui-widget-kpi-list' }
  } as WuiWidgetDatapointSettings;
}

// eslint-disable-next-line max-params -- positional grid placement reads clearly here
function ganttWidget(
  id: string,
  title: string,
  dpName: string,
  x: number,
  y: number,
  cols: number,
  rows: number
): WuiWidgetDatapointSettings {
  return {
    id,
    version: 2,
    x,
    y,
    cols,
    rows,
    minCols: GANTT_MIN,
    minRows: GANTT_MIN,
    name: title,
    settings: {
      jsonFileName: GANTT_JSON_FILE,
      general: generalBlock(title),
      config: groupCtx({
        variables: groupCtx({ sTimeRange: GANTT_RANGE }),
        showLegend: true,
        showXAxisGrid: false,
        showYAxisGrid: true,
        showRangePicker: true,
        showTooltip: true,
        showSeries: true,
        showMapping: true,
        xAxisPostion: 'bottom',
        yAxisPostion: 'left',
        zoom: true,
        series: arrayCtx([ganttSeriesItem(title, dpName)])
      })
    },
    component: { styles: [], scripts: ['gantt'], tagname: 'wui-widget-gantt' }
  } as WuiWidgetDatapointSettings;
}
