// SPDX-FileCopyrightText: 2026 VISUEL CONCEPT
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Role PROFILES — what each role implies in terms of WinCC OA configs. This is
 * what closes the loop: qualify the signals once (`./classify.ts`), and the model
 * check-in derives the address direction, the archiving, the alarm handling and
 * the value range from the role instead of asking per DPE.
 *
 * The shipped profiles are deliberately **NEUTRAL**:
 *  - archiving uses ONE group name, injected by the caller (default `EVENT`, the
 *    group every project has) — projects map roles to their own groups;
 *  - alarms use the `alert` class (the fallback already used by the PARA alarm
 *    tab) and a binary alert on TRUE;
 *  - **no `_pv_range` is generated by default**: a meaningful range is
 *    engineering knowledge (a type's numeric bounds would be a useless check),
 *    so a project profile must state fixed bounds for it to be written;
 *  - the address DIRECTION is derived from the signal's real access mode, and a
 *    profile may override it.
 *
 * Profiles are data: a project can replace any of them without touching code.
 */

import type { ArchiveConfig, AlarmConfig, BookEntry, RangeConfig } from '../model.js';
import { DpAddressDirection, directionFor } from '../drivers/opcua.js';
import type { SignalRole } from './roles.js';

/** How a role is turned into configs. */
export interface RoleProfile {
  /** Force the peripheral-address direction; omitted → derived from access. */
  direction?: 'in' | 'out' | 'inout';
  /** Archive this role (into `ctx.archiveGroup`), or explicitly not. */
  archive?: boolean;
  /** Generate a binary alert (alarms only). */
  alarm?: { kind: 'binary'; direction: 'ASC' | 'DESC' };
  /** Fixed value range — only written when a project states real bounds. */
  range?: { min: number; max: number; inclMin?: boolean; inclMax?: boolean };
}

/** Neutral, project-overridable profiles (see the module header). */
export const NEUTRAL_ROLE_PROFILES: Record<SignalRole, RoleProfile> = {
  measure: { direction: 'in', archive: true },
  setpoint: { direction: 'inout', archive: true },
  command: { direction: 'out', archive: true },
  state: { direction: 'in', archive: true },
  // A fault is read from the process and raises a binary alert on TRUE.
  alarm: { direction: 'in', archive: true, alarm: { kind: 'binary', direction: 'ASC' } },
  counter: { direction: 'in', archive: true },
  parameter: { archive: false },
  // An unqualified signal yields NO config — it must be qualified first.
  unknown: { archive: false }
};

/** Context supplied by the project (neutral defaults). */
export interface RoleProfileContext {
  /** NGA archive group used by every archived role. */
  archiveGroup?: string;
  /** Alert class used by the alarm role. */
  alarmClass?: string;
}

/** The configs a role implies for one entry (address direction + config bodies). */
export interface RoleConfigs {
  /** `_address.._direction` value. */
  direction: number;
  /**
   * Set when the role's WRITE intent had to be reconciled with an access mode the
   * source actually declares — the generator turns these into warnings, because a
   * silently downgraded command is a command that never reaches the machine.
   */
  directionNote?: string;
  archive?: ArchiveConfig;
  alarm?: AlarmConfig;
  range?: RangeConfig;
}

/** Whether the entry's access mode is EVIDENCE or just a default. */
function accessIsKnown(entry: BookEntry): boolean {
  return entry.accessSource !== 'assumed';
}

/**
 * Reconcile the role's INTENT with the signal's declared access mode.
 *
 * The two carry different information and neither may be ignored:
 *  - the role says what the signal is FOR (a command is written, a measure read);
 *  - the access mode says what the server/PLC actually ALLOWS.
 *
 * So:
 *  - access unknown (`assumed`, e.g. an online browse with no `AccessLevel`) →
 *    the role intent wins outright; the access carries no evidence;
 *  - intent to write + a read-only signal → the address is created as INPUT_POLL
 *    and a note is raised. Writing OUT on a read-only node yields a binding the
 *    server rejects at runtime — a silent, hard-to-diagnose failure;
 *  - intent to write + a write-only signal → OUTPUT (there is nothing to poll);
 *  - intent to read → INPUT_POLL even on a writable node: the studio only reads
 *    what the role reads (IO_POLL on a measure would declare a write path nobody
 *    uses);
 *  - no intent → the factual access mode decides.
 */
function resolveDirection(profile: RoleProfile, entry: BookEntry): { direction: number; note?: string } {
  const known = accessIsKnown(entry);
  switch (profile.direction) {
    case 'in': {
      return { direction: DpAddressDirection.INPUT_POLL };
    }
    case 'out': {
      if (!known || entry.access === 'w' || entry.access === 'rw') return { direction: DpAddressDirection.OUTPUT };
      return {
        direction: DpAddressDirection.INPUT_POLL,
        note: `« ${entry.path} » est déclaré en LECTURE SEULE par la source : adresse créée en entrée (IN) au lieu de sortie — corriger l’accès ou le rôle`
      };
    }
    case 'inout': {
      if (!known) return { direction: DpAddressDirection.IO_POLL };
      if (entry.access === 'rw') return { direction: DpAddressDirection.IO_POLL };
      if (entry.access === 'w') {
        return {
          direction: DpAddressDirection.OUTPUT,
          note: `« ${entry.path} » est déclaré en ÉCRITURE SEULE : adresse créée en sortie (OUT), la relecture de la consigne ne sera pas possible`
        };
      }
      return {
        direction: DpAddressDirection.INPUT_POLL,
        note: `« ${entry.path} » est déclaré en LECTURE SEULE par la source : adresse créée en entrée (IN) au lieu d’entrée/sortie — corriger l’accès ou le rôle`
      };
    }
    default: {
      // No intent stated by the profile: the source's own access mode decides.
      return { direction: directionFor(entry.access) };
    }
  }
}

/**
 * Derive the configs of one entry from its role.
 *
 * @param entry   the book entry (its access mode feeds the direction fallback)
 * @param role    the qualified role
 * @param profiles profile set (default: {@link NEUTRAL_ROLE_PROFILES})
 * @param ctx     project context (archive group, alarm class)
 */
export function configsForRole(
  entry: BookEntry,
  role: SignalRole,
  profiles: Record<SignalRole, RoleProfile> = NEUTRAL_ROLE_PROFILES,
  ctx: RoleProfileContext = {}
): RoleConfigs {
  const profile = profiles[role] ?? {};
  const resolved = resolveDirection(profile, entry);
  const result: RoleConfigs = { direction: resolved.direction };
  if (resolved.note !== undefined) result.directionNote = resolved.note;
  if (profile.archive) {
    result.archive = { group: ctx.archiveGroup ?? 'EVENT', active: true };
  }
  if (profile.alarm) {
    result.alarm = {
      kind: 'binary',
      alarmClass: ctx.alarmClass ?? 'alert',
      direction: profile.alarm.direction,
      active: true
    };
  }
  if (profile.range) {
    result.range = {
      min: profile.range.min,
      max: profile.range.max,
      inclMin: profile.range.inclMin ?? true,
      inclMax: profile.range.inclMax ?? true
    };
  }
  return result;
}

/** True when a role yields nothing to configure (must be qualified/ignored). */
export function roleIsInert(role: SignalRole, profiles: Record<SignalRole, RoleProfile> = NEUTRAL_ROLE_PROFILES): boolean {
  const profile = profiles[role] ?? {};
  return !profile.archive && profile.alarm === undefined && profile.range === undefined && profile.direction === undefined;
}
